name: metric_repository
description: "Handling metrics package."
version: 0.0.1
homepage:

environment:
  sdk: ">=3.4.1 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  bloc:
  flutter_bloc:
  equatable:
  http: any
  api_cache_manager: ^1.0.2
  archive: ^3.6.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

  user_repository:
    path: ../user_repository

flutter:
